### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by lboaventura25** [UnBForum/UnBForumDocs#12]
# TODO LIST - UnBFórum

### Para finalizar aplicação para testes

- [ ] Integração Downvote e upvote (FRONT) 
- [ ] Integração de filtros na Home page (FRONT, BACK pronto)
- [ ] Criação de tópico com categorias e multi select (FRONT, BACK pronto)
- [ ] Criação de tópico com criação de arquivos (FRONT, BACK expor pasta '/uploads')
- [ ] Ciação de categorias para os moderadores (FRONT, BACK pronto)
- [ ] Regras de negócio para checar se o usuário já votou no tópico (BACK, ajustes no FRONT)

### Para enviar TCC para Banca

- [x] Criar formulário para teste. (Validar com a Milene) **FEITO**
- [ ] Criar fluxos no Maze
- [ ]  Rodar 1° ciclo de testes
- [ ] Descrever resultados do 1° ciclo no Overleaf
- [ ] Fazer melhorias na aplicação
- [ ]  Rodar 2° ciclo de testes.
- [ ]  Descrever resultados do 2° ciclo no Overleaf
- [ ]  cap 5 adicionar como foi o desenvolvimento e etc
- [ ]  Fazer cap 7 com a nova conclusão
- [ ]  Enviar para a Milene
- [ ]  Realizar correções
